# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
include:
  - os: osx
  - r: release
  - r: oldrel
  - r: devel

after_success:
  - Rscript -e 'covr::codecov()'
