library(tibble)

test_that("Is identical to its stored reference", {
  expect_known_value(aerolineas(), "ref-airlines", update = FALSE)
  expect_known_value(aeropuertos(), "ref-airports", update = FALSE)
  expect_known_value(atmosfera(), "ref-atmos", update = FALSE)
  expect_known_value(premios_dirigentes(), "ref-awardmanagers", update = FALSE)
  expect_known_value(nombres(), "ref-babynames", update = FALSE)
  expect_known_value(bateadores(), "ref-batting", update = FALSE)
  expect_known_value(comunes(), "ref-common", update = FALSE)
  expect_known_value(diamantes(), "ref-diamonds", update = FALSE)
  expect_known_value(fiel(), "ref-faithful", update = FALSE)
  expect_known_value(jardineros(), "ref-fielding", update = FALSE)
  expect_known_value(vuelos(), "ref-flights", update = FALSE)
  expect_known_value(paises(), "ref-gapminder", update = FALSE)
  expect_known_value(encuesta(), "ref-gss-cats", update = FALSE)
  expect_known_value(flores(), "ref-iris", update = FALSE)
  expect_known_value(dirigentes(), "ref-managers", update = FALSE)
  expect_known_value(millas(), "ref-mpg", update = FALSE)
  expect_known_value(mtautos(), "ref-mtcars", update = FALSE)
  expect_known_value(personas(), "ref-people", update = FALSE)
  expect_known_value(lanzadores(), "ref-pitching", update = FALSE)
  expect_known_value(aviones(), "ref-planes", update = FALSE)
  expect_known_value(presidencial(), "ref-presidential", update = FALSE)
  expect_known_value(salarios(), "ref-salaries", update = FALSE)
  expect_known_value(tabla1(), "ref-table1", update = FALSE)
  expect_known_value(tabla2(), "ref-table2", update = FALSE)
  expect_known_value(tabla3(), "ref-table3", update = FALSE)
  expect_known_value(tabla4a(), "ref-table4a", update = FALSE)
  expect_known_value(tabla4b(), "ref-table4b", update = FALSE)
  expect_known_value(tabla5(), "ref-table5", update = FALSE)
  expect_known_value(vehiculos(), "ref-vehicles", update = FALSE)
  expect_known_value(clima(), "ref-weather", update = FALSE)
  expect_known_value(oms(), "ref-who", update = FALSE)

  verify_output(test_path("trans-output.txt"), {
    as_tibble(aerolineas())
    as_tibble(aeropuertos())
    as_tibble(atmosfera())
    as_tibble(premios_dirigentes())
    as_tibble(nombres())
    as_tibble(bateadores())
    as_tibble(comunes())
    as_tibble(diamantes())
    as_tibble(fiel())
    as_tibble(jardineros())
    as_tibble(vuelos())
    as_tibble(paises())
    as_tibble(encuesta())
    as_tibble(flores())
    as_tibble(dirigentes())
    as_tibble(millas())
    as_tibble(mtautos())
    as_tibble(personas())
    as_tibble(lanzadores())
    as_tibble(aviones())
    as_tibble(presidencial())
    as_tibble(salarios())
    as_tibble(tabla1())
    as_tibble(tabla2())
    as_tibble(tabla3())
    as_tibble(tabla4a())
    as_tibble(tabla4b())
    as_tibble(tabla5())
    as_tibble(vehiculos())
    as_tibble(clima())
    as_tibble(oms())
  })
})

